// user for offline users FIX or delete it
export const posts = [
  {
    id: "1",
    title: "The Catcher in the Rye",
    bookAuthor: "J.D. Salinger",
    desc: "The Catcher in the Rye is a novel by J.D. Salinger. It follows the story of Holden Caulfield, a disillusioned teenager who embarks on a journey of self-discovery and rebellion against societal norms. With its themes of alienation, identity, and teenage angst, the novel has become a classic of American literature. Salinger's masterful storytelling and Caulfield's unique voice have captivated readers for generations, making this book an essential read for anyone interested in coming-of-age tales and exploring the complexities of youth.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "2",
    title: "The Hobbit",
    bookAuthor: "J.R.R. Tolkien",
    desc: "The Hobbit, written by J.R.R. Tolkien, is an enchanting tale set in the fictional world of Middle-earth. It follows the journey of Bilbo Baggins, a hobbit who is reluctantly swept into an epic quest to reclaim the dwarf kingdom of Erebor from the fearsome dragon Smaug. Along the way, Bilbo encounters magical creatures, treacherous foes, and discovers courage he never knew he had. With its vivid descriptions, rich world-building, and themes of heroism and friendship, The Hobbit has captivated readers of all ages and has become a timeless classic of fantasy literature.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "3",
    title: "The Chronicles of Narnia",
    bookAuthor: "C.S. Lewis",
    desc: "The Chronicles of Narnia is a series of fantasy novels written by C.S. Lewis. The story takes place in the magical land of Narnia, a world inhabited by talking animals, mythical creatures, and enchanting landscapes. Through the adventures of the Pevensie children, the reader is transported into a realm where battles between good and evil, loyalty, bravery, and faith are explored. With its timeless themes and captivating storytelling, The Chronicles of Narnia has become a beloved series cherished by readers of all ages.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "4",
    title: "The Grapes of Wrath",
    bookAuthor: "John Steinbeck",
    desc: "The Grapes of Wrath is a novel by John Steinbeck that tells the story of the Joad family during the Great Depression. As they leave their drought-ridden farm in Oklahoma, they embark on a journey to California in search of a better life. Steinbeck's powerful depiction of poverty, injustice, and the resilience of the human spirit has made this book a classic of American literature. With its social commentary and timeless themes, The Grapes of Wrath continues to resonate with readers and shed light on the struggles faced by marginalized communities.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "5",
    title: "The Divine Comedy",
    bookAuthor: "Dante Alighieri",
    desc: "The Divine Comedy is an epic poem by Dante Alighieri, widely considered one of the greatest works of world literature. Divided into three parts—Inferno, Purgatorio, and Paradiso—the poem follows Dante's journey through Hell, Purgatory, and Heaven. It explores themes of sin, redemption, and the human condition. Through vivid imagery, intricate allegory, and philosophical insights, Dante takes readers on a spiritual and philosophical quest. The Divine Comedy continues to be celebrated for its literary genius and its profound exploration of the afterlife and the human soul.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "6",
    title: "Wuthering Heights",
    bookAuthor: "Emily Brontë",
    desc: "Wuthering Heights is a novel by Emily Brontë, a haunting tale of love, revenge, and passion set in the wild and windswept moors of Yorkshire. The story revolves around the intense and tumultuous relationship between Catherine Earnshaw and Heathcliff, an orphan brought to Wuthering Heights. Brontë's vivid descriptions, complex characters, and exploration of dark themes such as obsession and social class make Wuthering Heights a masterpiece of Gothic literature. It continues to captivate readers with its raw emotions and atmospheric setting.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "7",
    title: "Jane Eyre",
    bookAuthor: "Charlotte Brontë",
    desc: "Jane Eyre, written by Charlotte Brontë, is a bildungsroman that follows the life of the eponymous character. Orphaned as a child, Jane endures hardships and challenges but maintains her strong moral compass. The novel explores themes of love, independence, and the search for identity. With its rich characterization, atmospheric settings, and exploration of social and gender issues, Jane Eyre has become a classic of Victorian literature. Brontë's masterful storytelling and Jane's indomitable spirit continue to resonate with readers of all ages.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "8",
    title: "The Great Gatsby",
    bookAuthor: "F. Scott Fitzgerald",
    desc: "The Great Gatsby is a novel written by F. Scott Fitzgerald that explores themes of wealth, love, and the pursuit of the American Dream. Set in the Roaring Twenties, the story revolves around Jay Gatsby, a mysterious millionaire, and his obsession with the beautiful Daisy Buchanan. Fitzgerald's lyrical prose, vibrant characters, and critique of the Jazz Age have cemented The Great Gatsby as a classic of American literature. With its timeless themes and atmospheric setting, the novel continues to captivate readers and offer insights into the complexities of the human condition.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "9",
    title: "Moby-Dick",
    bookAuthor: "Herman Melville",
    desc: "Moby-Dick, written by Herman Melville, is an epic tale of obsession and revenge. The novel follows the adventures of Ishmael, a young sailor aboard the whaling ship Pequod, as he joins Captain Ahab's quest to hunt down the elusive white whale, Moby Dick. Melville's rich descriptions, philosophical musings, and exploration of themes such as the nature of evil and the human psyche have made Moby-Dick a literary masterpiece. It is celebrated for its depth, complexity, and timeless exploration of the human spirit's darkest depths.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "10",
    title: "Pride and Prejudice",
    bookAuthor: "Jane Austen",
    desc: "Pride and Prejudice, written by Jane Austen, is a beloved classic of English literature. Set in the early 19th century, the novel follows the story of the Bennet sisters and their quest for love and marriage. Through sharp wit, social commentary, and memorable characters such as Elizabeth Bennet and Mr. Darcy, Austen explores themes of societal expectations, class, and the complexities of relationships. With its timeless charm, sparkling dialogue, and Austen's astute observations of human nature, Pride and Prejudice remains a favorite among readers worldwide.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "11",
    title: "The Odyssey",
    bookAuthor: "Homer",
    desc: "The Odyssey is an ancient Greek epic poem attributed to Homer. It follows the hero Odysseus' ten-year journey home after the Trojan War. The poem is a sweeping adventure filled with mythical creatures, divine intervention, and tests of bravery and cunning. As Odysseus faces numerous challenges and battles, he seeks to return to his beloved homeland of Ithaca. The Odyssey has had a profound influence on Western literature and storytelling, and its exploration of themes such as heroism, destiny, and the power of storytelling continues to resonate with readers across the ages.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "12",
    title: "Don Quixote",
    bookAuthor: "Miguel de Cervantes",
    desc: "Don Quixote, written by Miguel de Cervantes, is considered one of the greatest works of fiction ever created. The novel follows the adventures of a middle-aged gentleman named Alonso Quixano, who becomes obsessed with chivalry books and sets out to revive knight-errantry. With his loyal squire Sancho Panza, Don Quixote embarks on a series of comical and often delusional adventures. Cervantes' masterpiece explores themes of reality versus illusion, idealism, and the power of imagination. Don Quixote continues to captivate readers with its blend of humor, satire, and profound reflections on the human condition.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "13",
    title: "War and Peace",
    bookAuthor: "Leo Tolstoy",
    desc: "War and Peace, written by Leo Tolstoy, is a sweeping epic that chronicles the lives of several Russian aristocratic families during the Napoleonic era. The novel explores themes of love, war, fate, and the human struggle for meaning and purpose. Tolstoy's rich characterizations, intricate plotting, and philosophical insights make War and Peace a masterpiece of world literature. With its vast scope, historical backdrop, and exploration of the complexities of human nature, the novel continues to captivate readers and offer profound insights into the human experience.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "14",
    title: "1984",
    bookAuthor: "George Orwell",
    desc: "1984 is a dystopian novel by George Orwell that portrays a totalitarian society ruled by a tyrannical government known as the Party. The story follows Winston Smith, a low-ranking Party member who rebels against the oppressive regime and attempts to preserve his individuality and freedom of thought. Orwell's chilling portrayal of surveillance, propaganda, and the manipulation of truth has made 1984 a classic and a cautionary tale about the dangers of authoritarianism. The novel continues to resonate with readers, reminding us of the importance of critical thinking and preserving our fundamental rights and freedoms.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "15",
    title: "The Lord of the Rings",
    bookAuthor: "J.R.R. Tolkien",
    desc: "The Lord of the Rings is a high fantasy novel by J.R.R. Tolkien that takes place in the fictional world of Middle-earth. The story follows Frodo Baggins, a hobbit tasked with destroying a powerful ring that could bring about the destruction of the world. With a richly imagined world, a diverse cast of characters, and themes of heroism, friendship, and the battle between good and evil, Tolkien's epic has captivated readers of all ages. The Lord of the Rings has become a cultural phenomenon and a landmark in fantasy literature, inspiring countless adaptations and sparking the imaginations of readers worldwide.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },

  {
    id: "16",
    title: "To Kill a Mockingbird",
    bookAuthor: "Harper Lee",
    desc: "To Kill a Mockingbird is a novel by Harper Lee that explores themes of racial injustice, moral courage, and the loss of innocence. Set in the Deep South during the 1930s, the story follows Scout Finch, a young girl, as she learns about empathy, compassion, and the importance of standing up for what is right. Through the character of Atticus Finch, Scout's father and a lawyer defending a black man wrongly accused of rape, Lee addresses issues of prejudice and the power of perspective. To Kill a Mockingbird has become a classic of American literature, celebrated for its powerful storytelling and enduring messages.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "17",
    title: "The Catcher in the Rye",
    bookAuthor: "J.D. Salinger",
    desc: "The Catcher in the Rye, written by J.D. Salinger, is a coming-of-age novel that has resonated with generations of readers. The story is narrated by Holden Caulfield, a disillusioned teenager who struggles with alienation, identity, and the hypocrisy of the adult world. Salinger's honest and introspective portrayal of adolescence and the search for meaning has made The Catcher in the Rye a modern classic. The novel continues to engage readers with its authentic voice, poignant observations, and exploration of themes such as innocence, rebellion, and the longing for connection.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "18",
    title: "The Hobbit",
    bookAuthor: "J.R.R. Tolkien",
    desc: "The Hobbit, written by J.R.R. Tolkien, is a fantasy adventure novel set in the world of Middle-earth. The story follows Bilbo Baggins, a hobbit who embarks on a quest with a group of dwarves to reclaim their homeland from the dragon Smaug. Along the way, Bilbo encounters trolls, goblins, elves, and other fantastical creatures. With its charming narrative style, memorable characters, and rich world-building, The Hobbit has captured the hearts of readers of all ages. It serves as a prelude to Tolkien's epic trilogy, The Lord of the Rings, and offers a delightful and enchanting journey into a world of magic and adventure.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "19",
    title: "The Chronicles of Narnia",
    bookAuthor: "C.S. Lewis",
    desc: "The Chronicles of Narnia is a series of fantasy novels written by C.S. Lewis. The story follows a group of children who stumble upon a magical wardrobe that leads them to the enchanted land of Narnia. As they journey through Narnia, they encounter talking animals, mythical creatures, and epic battles between good and evil. Lewis' imaginative storytelling, rich symbolism, and exploration of themes such as faith, courage, and redemption have made The Chronicles of Narnia a beloved classic. The series has captivated readers with its enchanting world and timeless lessons about love, loyalty, and the power of imagination.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "20",
    title: "The Alchemist",
    bookAuthor: "Paulo Coelho",
    desc: "The Alchemist, written by Paulo Coelho, is a philosophical novel that tells the story of a young Andalusian shepherd named Santiago and his journey to discover his personal legend. Set in the mystical desert landscapes of Egypt, the novel explores themes of destiny, self-discovery, and the pursuit of one's dreams. Through allegorical storytelling and profound insights, Coelho invites readers to reflect on the meaning of life and the importance of listening to one's heart. The Alchemist has become an international bestseller, captivating readers with its inspirational message and timeless wisdom.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "21",
    title: "The Brothers Karamazov",
    bookAuthor: "Fyodor Dostoevsky",
    desc: "The Brothers Karamazov, written by Fyodor Dostoevsky, is a philosophical novel that explores the depths of human nature, morality, and spirituality. Set in 19th-century Russia, the story follows the tumultuous lives of the Karamazov family and their struggles with faith, guilt, and the consequences of their actions. Dostoevsky's masterful storytelling, complex characters, and exploration of existential themes have made The Brothers Karamazov a literary masterpiece. The novel delves into profound philosophical questions and offers profound insights into the human condition, making it a thought-provoking and enduring work of literature.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "22",
    title: "Brave New World",
    bookAuthor: "Aldous Huxley",
    desc: "Brave New World is a dystopian novel by Aldous Huxley that presents a vision of a future society that is controlled by technology, consumerism, and social conditioning. Set in a world where humans are genetically engineered and society is organized to promote stability and conformity, the novel explores themes of individuality, freedom, and the price of happiness. Huxley's prophetic vision of a dehumanized society has made Brave New World a classic of dystopian literature. The novel continues to challenge readers with its critique of the dangers of a technocratic society and the loss of human values.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "23",
    title: "The Divine Comedy",
    bookAuthor: "Dante Alighieri",
    desc: "The Divine Comedy, written by Dante Alighieri, is an epic poem that takes readers on a journey through the realms of the afterlife. Divided into three parts—Inferno, Purgatorio, and Paradiso—the poem follows the protagonist, Dante, as he explores Hell, climbs the Mount of Purgatory, and ascends to Heaven. Through vivid imagery, allegory, and philosophical reflections, Dante examines themes of sin, redemption, and the human condition. The Divine Comedy is regarded as one of the greatest works of world literature and has influenced countless writers and artists throughout the centuries.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
  {
    id: "24",
    title: "Moby-Dick",
    bookAuthor: "Herman Melville",
    desc: "Moby-Dick, written by Herman Melville, is a novel that explores themes of obsession, revenge, and the nature of humanity. The story follows Captain Ahab and his quest to hunt down the great white whale, Moby Dick, who has taken his leg. Set aboard the whaling ship Pequod, the novel delves into the psychological depths of its characters and examines the power of nature and the destructive forces of human desire. Melville's rich prose, vivid descriptions, and exploration of existential themes have made Moby-Dick a literary masterpiece that continues to captivate readers and provoke thought.",
    coverUrl: "",
    likes: [],
    createdBy: "649b63dd9413886ed7069617",
  },
];
